### ISSUE TITLE
Refacere istoric commit-uri

### ISSUE THREAD

**Issue by dan-avram-selab** [ana0009/Tema1#2]
Aveti 8 commit-uri pentru o treaba de 2 commit-uri. Refaceti istoricul sa fie cum am cerut initial: 2 commituri(adaugare readme + adaugare .gitignore)

Fie faceti local un repository nou si dati push -f pe server, fie faceti rebase interactiv si stergeti ultimele commituri apoi rescrieti-le pe primele doua.

**Comment by ana0009** [comment]
Am rezolvat.
